{% set name = "pyberny" %}
{% set version = "0.6.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyberny-{{ version }}.tar.gz
  sha256: b4bd9d3d2d58261e8f1d91b8204cc563617044d4b9daf6aae8feee31893cb336

build:
  entry_points:
    - berny = berny.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - poetry-dynamic-versioning >=0.12.3
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.15.0,<2.0.0

test:
  imports:
    - berny
  commands:
    - pip check
    - berny --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jhrmnn/pyberny
  summary: Molecular/crystal structure optimizer
  license: MPL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - awvwgk
